# Inspired by https://blog.devgenius.io/how-to-deploy-a-mongodb-replicaset-using-docker-compose-a538100db471
version: '3'

services:
  mongo1:
    container_name: mongo1
    image: mongo:6.0.3
    volumes:
      - ./scripts:/scripts
    networks:
      - mongodb-network
    ports:
      - 27017:27017
    depends_on:
      - mongo2
      - mongo3
      - mongo4
      - mongo5
      - mongo6
    links:
      - mongo2
      - mongo3
      - mongo4
      - mongo5
      - mongo6
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo2:
    container_name: mongo2
    image: mongo:6.0.3
    networks:
      - mongodb-network
    ports:
      - 27018:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo3:
    container_name: mongo3
    image: mongo:6.0.3
    networks:
      - mongodb-network
    ports:
      - 27019:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo4:
    container_name: mongo4
    image: mongo:6.0.3
    networks:
      - mongodb-network
    ports:
      - 27020:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo5:
    container_name: mongo5
    image: mongo:6.0.3
    networks:
      - mongodb-network
    ports:
      - 27021:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo6:
    container_name: mongo6
    image: mongo:6.0.3
    networks:
      - mongodb-network
    ports:
      - 27022:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

networks:
  mongodb-network:
    driver: bridge