#https://github.com/bitnami/bitnami-docker-redis-cluster/blob/master/docker-compose.yml
version: '2'
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:latest
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:latest
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:latest
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_CLUSTER_CREATOR=yes'

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local